version: '3.9'
services:
  nginx:
    image: nginx:stable
    restart: always
    container_name: 'sportisimo-marks-nginx'
    ports:
      - "80:80"
    volumes:
      - www:/var/www/assets/
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
  php:
    build: .
    container_name: 'sportisimo-marks-php'
    volumes:
      - www:/var/www-marks/www/assets/
      - ./log/:/var/log/www-marks/

volumes:
  www:
