USE marks;

INSERT INTO mark (id, name)
VALUES  (1, 'Abus'),
        (2, 'adidas'),
        (3, 'Alapai'),
        (4, 'ALFA'),
        (5, 'Alice Company'),
        (6, 'Alpina'),
        (7, 'ALPINE PRO'),
        (8, 'AQUOS'),
        (9, 'Arcore'),
        (10, 'Ares'),
        (11, 'Asics'),
        (12, 'Atomic'),
        (13, 'Avenue'),
        (14, 'AXA'),
        (15, 'Axis'),
        (16, 'BAAGL'),
        (17, 'Babolat'),
        (18, 'BABY JOGGER'),
        (19, 'BABYAUTO'),
        (20, 'BABYPACK'),
        (21, 'BAG BOY'),
        (22, 'Bauer'),
        (23, 'BCA'),
        (24, 'BLUETOUCH'),
        (25, 'Bliz'),
        (26, 'BOATILUS'),
        (27, 'Calvin Klein'),
        (28, 'CALYPSO'),
        (29, 'CAMP'),
        (30, 'Campingaz'),
        (31, 'CANONDALE'),
        (32, 'CAPITAL SPORTS'),
        (33, 'Castelli'),
        (34, 'CCM'),
        (35, 'Cebe'),
        (36, 'CMP'),
        (37, 'COBRA'),
        (38, 'Coleman'),
        (39, 'Columbia'),
        (40, 'Compostick'),
        (41, 'Crowned'),
        (42, 'Craft'),
        (43, 'Daehlie'),
        (44, 'Dakine'),
        (45, 'Devold'),
        (46, 'DC'),
        (47, 'Zealot'),
        (48, 'Zray'),
        (49, 'Zone'),
        (50, 'Ziener'),
        (51, '4KAAD'),
        (52, 'Yedoo'),
        (53, 'XD Design'),
        (54, 'K2'),
        (55, 'Kama'),
        (56, 'Kappa'),
        (57, 'KARI TRAA'),
        (58, 'Kross'),
        (59, 'Level'),
        (60, 'La Siesta');
INSERT INTO mark (id, name)
VALUES  (61, 'Olympia');
